config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do

  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
belongs_to :user 
belongs_to :book

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new

  end

  def destroy
    #byebug
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy 
    #id: params[:id], book_id: params[:book_id]の情報はlink_toでの引数で渡しているため
    #削除を押した時点で情報は特定できている、どちらかの情報を渡すだけでrailsが勝手に読み込む
    @book = Book.find(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
   <%= form_with model: [book, book_comment],  local: false do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "w-100" %>
    <%= f.submit "送信" ,class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  <% end %>

app/views/book_comments/_comments_count.html.erb
コメント件数：<%= book.book_comments.count %>

app/views/book_comments/_index.html.erb
<table>
       <% book.book_comments.each do |book_comment| %>
       <tr>
        <td>
         <p><%= image_tag book_comment.user.get_profile_image, size:'50x50' %></p>
         <%= book_comment.user.name %>
        </td>
        <td>
         <%= book_comment.comment %>
        </td>
        <td>
         <% if book_comment.user == current_user %>
          <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
         <% end %>

        </td>
       <% end %>
        </td>
       </tr>
      </table>

app/views/book_comments/create.js.erb
$('#comment-index').html("<%= j(render partial: 'book_comments/index', locals: { book: @book }) %>");
$('#comment-area').html("<%= j(render partial: 'book_comments/comment', locals: { book: @book, book_comment: @book_comment }) %>");
$(".book-comments-counter").html("コメント件数：<%= @book.book_comments.count %>");

app/views/book_comments/destroy.js.erb
$('#comment-index').html("<%= j(render partial: 'book_comments/index', locals: { book: @book }) %>");